apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sentinelai

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: sentinelai

resources:
  - namespace.yml
  - configmap.yml
  - secrets.yml
  - backend-deployment.yml
  - backend-service.yml
  - frontend-deployment.yml
  - frontend-service.yml
  - ingress.yml
  - hpa.yml
  - network-policy.yml
